name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:  # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Log deployment configuration
      run: |
        echo "Deploying to AWS Elastic Beanstalk"
        echo "Application Name: ${{ secrets.EB_APPLICATION_NAME }}"
        echo "Environment Name: ${{ secrets.EB_ENVIRONMENT_NAME }}"
        echo "AWS Region: ${{ secrets.AWS_REGION }}"
        echo "Version Label (Git SHA): ${{ github.sha }}"

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build


    - name: Zip application for Elastic Beanstalk
      run: |
        zip -r deploy.zip . -x "*.git*" "*.github*" "node_modules/*"

    - name: List contents (for debug)
      run: ls -lh deploy.zip


    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
        region: ${{ secrets.AWS_REGION }}
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip

